<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Unidad 3: Preprocesamiento y visualización | Propuesta — Series de Tiempo (Kaggle: Australia Monthly Retail Turnover)</title>
  <meta name="description" content="4 Unidad 3: Preprocesamiento y visualización | Propuesta — Series de Tiempo (Kaggle: Australia Monthly Retail Turnover)" />
  <meta name="generator" content="bookdown 0.41 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Unidad 3: Preprocesamiento y visualización | Propuesta — Series de Tiempo (Kaggle: Australia Monthly Retail Turnover)" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Unidad 3: Preprocesamiento y visualización | Propuesta — Series de Tiempo (Kaggle: Australia Monthly Retail Turnover)" />
  
  
  

<meta name="author" content="Edgar Esteban Grajales, Kassandra Mendoza-Sarmiento y Paula Tovar Ríos" />


<meta name="date" content="2025-11-15" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="unidad-2.-análisis-descriptivo-y-estructural-de-una-serie-temporal-tendencia-estacionalidad-y-estacionariedad.html"/>
<link rel="next" href="unidad-4-metodología-holter-winter-y-suavizamiento-a-la-variable-tiempo.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">📊 Series de Tiempo - Kaggle Retail Turnover</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="#introducci%C3%B3n"><i class="fa fa-check"></i><b>1</b> Introducción</a></li>
<li class="chapter" data-level="2" data-path="index.html"><a href="#unidad-1.-propuesta-de-informaci%C3%B3n-a-pronosticar"><i class="fa fa-check"></i><b>2</b> Unidad 1. Propuesta de información a pronosticar</a>
<ul>
<li class="chapter" data-level="2.1" data-path="unidad-1.-propuesta-de-información-a-pronosticar.html"><a href="unidad-1.-propuesta-de-información-a-pronosticar.html"><i class="fa fa-check"></i><b>2.1</b> <strong>Tema y base de datos</strong></a></li>
<li class="chapter" data-level="2.2" data-path="unidad-1.-propuesta-de-información-a-pronosticar.html"><a href="unidad-1.-propuesta-de-información-a-pronosticar.html#importancia-y-valor-agregado"><i class="fa fa-check"></i><b>2.2</b> <strong>Importancia y valor agregado</strong></a></li>
<li class="chapter" data-level="2.3" data-path="unidad-1.-propuesta-de-información-a-pronosticar.html"><a href="unidad-1.-propuesta-de-información-a-pronosticar.html#alcance-propuesto"><i class="fa fa-check"></i><b>2.3</b> <strong>Alcance propuesto</strong></a></li>
<li class="chapter" data-level="2.4" data-path="unidad-1.-propuesta-de-información-a-pronosticar.html"><a href="unidad-1.-propuesta-de-información-a-pronosticar.html#conclusiones-unidad-1"><i class="fa fa-check"></i><b>2.4</b> <strong>Conclusiones Unidad 1</strong></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="index.html"><a href="#unidad-2.-an%C3%A1lisis-descriptivo-y-estructural-de-una-serie-temporal-tendencia-estacionalidad-y-estacionariedad"><i class="fa fa-check"></i><b>3</b> Unidad 2. Análisis descriptivo y estructural de una serie temporal: tendencia, estacionalidad y estacionariedad</a>
<ul>
<li class="chapter" data-level="3.1" data-path="index.html"><a href="#descripci%C3%B3n-y-justificaci%C3%B3n-del-conjunto-de-datos"><i class="fa fa-check"></i><b>3.1</b> <strong>Descripción y justificación del conjunto de datos</strong></a></li>
<li class="chapter" data-level="3.2" data-path="index.html"><a href="#preparaci%C3%B3n-y-filtrado-de-datos-serie-total-mensual"><i class="fa fa-check"></i><b>3.2</b> <strong>Preparación y filtrado de datos: serie total mensual</strong></a></li>
<li class="chapter" data-level="3.3" data-path="index.html"><a href="#construcci%C3%B3n-de-la-serie-temporal"><i class="fa fa-check"></i><b>3.3</b> <strong>Construcción de la serie temporal</strong></a></li>
<li class="chapter" data-level="3.4" data-path="index.html"><a href="#promedios-m%C3%B3viles-smaema-y-an%C3%A1lisis-de-tendencia"><i class="fa fa-check"></i><b>3.4</b> <strong>Promedios móviles (SMA/EMA) y análisis de tendencia</strong></a></li>
<li class="chapter" data-level="3.5" data-path="index.html"><a href="#estacionalidad-y-rezagos-seasonplot-subseries-acf-y-descomposici%C3%B3n"><i class="fa fa-check"></i><b>3.5</b> <strong>Estacionalidad y rezagos (seasonplot, subseries, ACF y descomposición)</strong></a></li>
<li class="chapter" data-level="3.6" data-path="index.html"><a href="#diferencias-%CE%B4-y-%CE%B4%E2%82%81%E2%82%82-rezagos-y-estabilizaci%C3%B3n"><i class="fa fa-check"></i><b>3.6</b> <strong>Diferencias Δ y Δ₁₂ (rezagos y estabilización)</strong></a></li>
<li class="chapter" data-level="3.7" data-path="unidad-2.-análisis-descriptivo-y-estructural-de-una-serie-temporal-tendencia-estacionalidad-y-estacionariedad.html"><a href="unidad-2.-análisis-descriptivo-y-estructural-de-una-serie-temporal-tendencia-estacionalidad-y-estacionariedad.html"><i class="fa fa-check"></i><b>3.7</b> <strong>Conclusiones unidad 2</strong></a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="index.html"><a href="#unidad-3-preprocesamiento-y-visualizaci%C3%B3n"><i class="fa fa-check"></i><b>4</b> Unidad 3: Preprocesamiento y visualización</a>
<ul>
<li class="chapter" data-level="4.1" data-path="index.html"><a href="#transformaci%C3%B3n-box-cox-descomposici%C3%B3n-stl"><i class="fa fa-check"></i><b>4.1</b> <strong>Transformación Box-Cox + Descomposición STL</strong></a></li>
<li class="chapter" data-level="4.2" data-path="index.html"><a href="#fuerza-estacional-recomendaciones-de-diferenciaci%C3%B3n"><i class="fa fa-check"></i><b>4.2</b> <strong>Fuerza estacional + recomendaciones de diferenciación</strong></a></li>
<li class="chapter" data-level="4.3" data-path="index.html"><a href="#doble-diferenciaci%C3%B3n-regular-y-estacional"><i class="fa fa-check"></i><b>4.3</b> <strong>Doble diferenciación (regular y estacional)</strong></a></li>
<li class="chapter" data-level="4.4" data-path="index.html"><a href="#prueba-adf-antesdespu%C3%A9s"><i class="fa fa-check"></i><b>4.4</b> <strong>Prueba ADF antes/después</strong></a></li>
<li class="chapter" data-level="4.5" data-path="index.html"><a href="#validaci%C3%B3n-visual-acf-y-pacf"><i class="fa fa-check"></i><b>4.5</b> <strong>Validación visual: ACF y PACF</strong></a></li>
<li class="chapter" data-level="4.6" data-path="unidad-3-preprocesamiento-y-visualización.html"><a href="unidad-3-preprocesamiento-y-visualización.html"><i class="fa fa-check"></i><b>4.6</b> <strong>Conclusiones unidad 3</strong></a></li>
<li class="chapter" data-level="4.7" data-path="unidad-3-preprocesamiento-y-visualización.html"><a href="unidad-3-preprocesamiento-y-visualización.html#referencias"><i class="fa fa-check"></i><b>4.7</b> <strong>Referencias</strong></a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="index.html"><a href="#unidad-4-metodolog%C3%ADa-holter-winter-y-suavizamiento-a-la-variable-tiempo"><i class="fa fa-check"></i><b>5</b> Unidad 4: Metodología Holter-Winter y suavizamiento a la variable tiempo</a>
<ul>
<li class="chapter" data-level="5.1" data-path="unidad-4-metodología-holter-winter-y-suavizamiento-a-la-variable-tiempo.html"><a href="unidad-4-metodología-holter-winter-y-suavizamiento-a-la-variable-tiempo.html"><i class="fa fa-check"></i><b>5.1</b> Ajuste de modelos Holt–Winters</a></li>
<li class="chapter" data-level="5.2" data-path="index.html"><a href="#gr%C3%A1ficas-de-pron%C3%B3stico-y-bandas"><i class="fa fa-check"></i><b>5.2</b> Gráficas de pronóstico y bandas</a></li>
<li class="chapter" data-level="5.3" data-path="index.html"><a href="#diagn%C3%B3sticos-de-residuales"><i class="fa fa-check"></i><b>5.3</b> Diagnósticos de residuales</a></li>
<li class="chapter" data-level="5.4" data-path="unidad-4-metodología-holter-winter-y-suavizamiento-a-la-variable-tiempo.html"><a href="unidad-4-metodología-holter-winter-y-suavizamiento-a-la-variable-tiempo.html#conclusiones"><i class="fa fa-check"></i><b>5.4</b> Conclusiones</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="unidad-5-modelos-estacionarios-en-series-de-tiempo.html"><a href="unidad-5-modelos-estacionarios-en-series-de-tiempo.html"><i class="fa fa-check"></i><b>6</b> Unidad 5: Modelos estacionarios en series de tiempo</a>
<ul>
<li class="chapter" data-level="6.1" data-path="index.html"><a href="#evaluaci%C3%B3n-de-estacionariedad"><i class="fa fa-check"></i><b>6.1</b> Evaluación de estacionariedad</a></li>
<li class="chapter" data-level="6.2" data-path="index.html"><a href="#identificaci%C3%B3n-y-estimaci%C3%B3n-del-modelo-arima"><i class="fa fa-check"></i><b>6.2</b> Identificación y estimación del modelo ARIMA</a></li>
<li class="chapter" data-level="6.3" data-path="index.html"><a href="#diagn%C3%B3stico-de-residuales"><i class="fa fa-check"></i><b>6.3</b> Diagnóstico de residuales</a></li>
<li class="chapter" data-level="6.4" data-path="index.html"><a href="#pron%C3%B3stico-del-modelo"><i class="fa fa-check"></i><b>6.4</b> Pronóstico del modelo</a></li>
<li class="chapter" data-level="6.5" data-path="index.html"><a href="#conclusi%C3%B3n-modelos-estacionarios"><i class="fa fa-check"></i><b>6.5</b> Conclusión modelos estacionarios</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="index.html"><a href="#unidad-6-modelo-prophet-y-serie-de-tiempo-como-regresi%C3%B3n-en-el-tiempo"><i class="fa fa-check"></i><b>7</b> Unidad 6: Modelo Prophet y serie de tiempo como regresión en el tiempo</a>
<ul>
<li class="chapter" data-level="7.1" data-path="unidad-6-modelo-prophet-y-serie-de-tiempo-como-regresión-en-el-tiempo.html"><a href="unidad-6-modelo-prophet-y-serie-de-tiempo-como-regresión-en-el-tiempo.html"><i class="fa fa-check"></i><b>7.1</b> Fundamentos del modelo Prophet</a></li>
<li class="chapter" data-level="7.2" data-path="index.html"><a href="#preparaci%C3%B3n-de-datos-y-ajuste-del-modelo-prophet"><i class="fa fa-check"></i><b>7.2</b> Preparación de datos y ajuste del modelo Prophet</a></li>
<li class="chapter" data-level="7.3" data-path="index.html"><a href="#ajuste-del-modelo-prophet-y-an%C3%A1lisis-de-componentes"><i class="fa fa-check"></i><b>7.3</b> Ajuste del modelo Prophet y análisis de componentes</a></li>
<li class="chapter" data-level="7.4" data-path="index.html"><a href="#comparaci%C3%B3n-de-desempe%C3%B1o-entre-holtwinters-arima-y-prophet"><i class="fa fa-check"></i><b>7.4</b> Comparación de desempeño entre Holt–Winters, ARIMA y Prophet</a></li>
<li class="chapter" data-level="7.5" data-path="index.html"><a href="#comparaci%C3%B3n-de-modelos-y-conclusiones"><i class="fa fa-check"></i><b>7.5</b> Comparación de modelos y conclusiones</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/paolat87/1_Act_Series_de_tiempo_Bookdown" target="_blank">🌐 Publicado con bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Propuesta — Series de Tiempo (Kaggle: Australia Monthly Retail Turnover)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="unidad-3-preprocesamiento-y-visualización" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">4</span> Unidad 3: Preprocesamiento y visualización<a href="#unidad-3-preprocesamiento-y-visualizaci%C3%B3n" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>En esta unidad se continúa el análisis desarrollado en la Unidad 2, profundizando en las etapas de preprocesamiento de datos y visualización aplicadas a la serie mensual Australia Monthly Retail Turnover (1982–2024). El objetivo es garantizar que la serie cumpla con las condiciones necesarias para su posterior modelado, particularmente en la identificación de componentes estructurales y la estabilización de la varianza y la media.</p>
<p>A través de técnicas estadísticas y gráficas, se analizan nuevamente los patrones de tendencia y estacionalidad, la descomposición de la serie y las transformaciones requeridas para alcanzar la estacionariedad, utilizando funciones de diferenciación regular y estacional (Δ y Δ₁₂). Estas operaciones forman parte esencial del preprocesamiento, al eliminar dependencias sistemáticas y preparar la información para la estimación de modelos ARIMA estacionales (SARIMA).</p>
<p>El proceso descrito integra la manipulación de datos, la verificación de supuestos y la interpretación visual como base para la comprensión del comportamiento temporal de las ventas minoristas australianas, asegurando una estructura adecuada y confiable para las fases siguientes de modelado y validación.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="unidad-3-preprocesamiento-y-visualización.html#cb40-1" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>({</span>
<span id="cb40-2"><a href="unidad-3-preprocesamiento-y-visualización.html#cb40-2" tabindex="-1"></a>  <span class="fu">library</span>(forecast); <span class="fu">library</span>(tseries); <span class="fu">library</span>(ggplot2)</span>
<span id="cb40-3"><a href="unidad-3-preprocesamiento-y-visualización.html#cb40-3" tabindex="-1"></a>  <span class="fu">library</span>(knitr);    <span class="fu">library</span>(kableExtra)</span>
<span id="cb40-4"><a href="unidad-3-preprocesamiento-y-visualización.html#cb40-4" tabindex="-1"></a>})</span>
<span id="cb40-5"><a href="unidad-3-preprocesamiento-y-visualización.html#cb40-5" tabindex="-1"></a></span>
<span id="cb40-6"><a href="unidad-3-preprocesamiento-y-visualización.html#cb40-6" tabindex="-1"></a><span class="co"># Estilos</span></span>
<span id="cb40-7"><a href="unidad-3-preprocesamiento-y-visualización.html#cb40-7" tabindex="-1"></a>gg_std <span class="ot">&lt;-</span> <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">11</span>) <span class="sc">+</span></span>
<span id="cb40-8"><a href="unidad-3-preprocesamiento-y-visualización.html#cb40-8" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb40-9"><a href="unidad-3-preprocesamiento-y-visualización.html#cb40-9" tabindex="-1"></a>    <span class="at">plot.title.position =</span> <span class="st">&quot;plot&quot;</span>,</span>
<span id="cb40-10"><a href="unidad-3-preprocesamiento-y-visualización.html#cb40-10" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>),</span>
<span id="cb40-11"><a href="unidad-3-preprocesamiento-y-visualización.html#cb40-11" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">&quot;grey30&quot;</span>),</span>
<span id="cb40-12"><a href="unidad-3-preprocesamiento-y-visualización.html#cb40-12" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>()</span>
<span id="cb40-13"><a href="unidad-3-preprocesamiento-y-visualización.html#cb40-13" tabindex="-1"></a>  )</span>
<span id="cb40-14"><a href="unidad-3-preprocesamiento-y-visualización.html#cb40-14" tabindex="-1"></a></span>
<span id="cb40-15"><a href="unidad-3-preprocesamiento-y-visualización.html#cb40-15" tabindex="-1"></a>kbl_std <span class="ot">&lt;-</span> <span class="cf">function</span>(df, <span class="at">caption =</span> <span class="cn">NULL</span>, <span class="at">digits =</span> <span class="dv">3</span>) {</span>
<span id="cb40-16"><a href="unidad-3-preprocesamiento-y-visualización.html#cb40-16" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(df, <span class="at">caption =</span> caption, <span class="at">align =</span> <span class="st">&quot;c&quot;</span>, <span class="at">digits =</span> digits) <span class="sc">|&gt;</span></span>
<span id="cb40-17"><a href="unidad-3-preprocesamiento-y-visualización.html#cb40-17" tabindex="-1"></a>    kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>, <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">&quot;striped&quot;</span>, <span class="st">&quot;hover&quot;</span>))</span>
<span id="cb40-18"><a href="unidad-3-preprocesamiento-y-visualización.html#cb40-18" tabindex="-1"></a>}</span></code></pre></div>
<div id="transformación-box-cox-descomposición-stl" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> <strong>Transformación Box-Cox + Descomposición STL</strong><a href="#transformaci%C3%B3n-box-cox-descomposici%C3%B3n-stl" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La transformación Box–Cox se utiliza para estabilizar la varianza y mejorar la normalidad de una serie temporal antes del modelado.</p>
<p>Fórmula:</p>
<p><span class="math display">\[
Y&#39;_t =
\begin{cases}
\frac{Y_t^{\lambda} - 1}{\lambda}, &amp; \text{si } \lambda \neq 0 \\
\ln(Y_t), &amp; \text{si } \lambda = 0
\end{cases}
\]</span>
𝑌𝑡 es el valor original de la serie,</p>
<p>𝑌𝑡 es la serie transformada,</p>
<p>𝜆 es el parámetro que controla el grado de transformación (estimado con BoxCox.lambda()).</p>
<p>Interpretación práctica:</p>
<p>Si 𝜆≈1, no es necesaria la transformación.</p>
<p>Si 𝜆&lt;1, se recomienda aplicar la transformación (reduce la dispersión).</p>
<p>La descomposición STL permite expresar una serie temporal 𝑌𝑡como la suma de tres componentes:</p>
<p><span class="math display">\[Y_t = T_t + S_t + R_t\]</span></p>
<p>donde:</p>
<p>𝑇𝑡 es la tendencia,</p>
<p>𝑆𝑡 la estacionalidad,</p>
<p>𝑅𝑡 el residuo o componente irregular.</p>
<p>El método STL aplica suavizamiento LOESS para estimar cada componente, permitiendo manejar estacionalidad no constante y valores atípicos.</p>
<p>El propósito es separar los efectos estructurales (tendencia y estacionalidad) de los componentes aleatorios, facilitando el análisis de estacionariedad.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="unidad-3-preprocesamiento-y-visualización.html#cb41-1" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">exists</span>(<span class="st">&quot;ts_y&quot;</span>), <span class="fu">is.ts</span>(ts_y), <span class="fu">frequency</span>(ts_y) <span class="sc">==</span> <span class="dv">12</span>)</span>
<span id="cb41-2"><a href="unidad-3-preprocesamiento-y-visualización.html#cb41-2" tabindex="-1"></a></span>
<span id="cb41-3"><a href="unidad-3-preprocesamiento-y-visualización.html#cb41-3" tabindex="-1"></a>lambda_bc <span class="ot">&lt;-</span> <span class="fu">BoxCox.lambda</span>(ts_y)</span>
<span id="cb41-4"><a href="unidad-3-preprocesamiento-y-visualización.html#cb41-4" tabindex="-1"></a>usar_bc   <span class="ot">&lt;-</span> <span class="fu">abs</span>(lambda_bc <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">&gt;</span> <span class="fl">0.1</span></span>
<span id="cb41-5"><a href="unidad-3-preprocesamiento-y-visualización.html#cb41-5" tabindex="-1"></a></span>
<span id="cb41-6"><a href="unidad-3-preprocesamiento-y-visualización.html#cb41-6" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;λ (Box-Cox) estimado:&quot;</span>, <span class="fu">round</span>(lambda_bc, <span class="dv">3</span>), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## λ (Box-Cox) estimado: 0.196</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="unidad-3-preprocesamiento-y-visualización.html#cb43-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;¿Aplicar transformación? &quot;</span>, <span class="fu">ifelse</span>(usar_bc, <span class="st">&quot;Sí (|λ−1|&gt;0.1)&quot;</span>, <span class="st">&quot;No (λ≈1)&quot;</span>), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## ¿Aplicar transformación?  Sí (|λ−1|&gt;0.1)</code></pre>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="unidad-3-preprocesamiento-y-visualización.html#cb45-1" tabindex="-1"></a>serie_bc <span class="ot">&lt;-</span> <span class="cf">if</span> (usar_bc) <span class="fu">BoxCox</span>(ts_y, lambda_bc) <span class="cf">else</span> ts_y</span>
<span id="cb45-2"><a href="unidad-3-preprocesamiento-y-visualización.html#cb45-2" tabindex="-1"></a></span>
<span id="cb45-3"><a href="unidad-3-preprocesamiento-y-visualización.html#cb45-3" tabindex="-1"></a>stl_obj <span class="ot">&lt;-</span> <span class="fu">stl</span>(serie_bc, <span class="at">s.window =</span> <span class="st">&quot;periodic&quot;</span>, <span class="at">robust =</span> <span class="cn">TRUE</span>)</span>
<span id="cb45-4"><a href="unidad-3-preprocesamiento-y-visualización.html#cb45-4" tabindex="-1"></a></span>
<span id="cb45-5"><a href="unidad-3-preprocesamiento-y-visualización.html#cb45-5" tabindex="-1"></a><span class="fu">print</span>(</span>
<span id="cb45-6"><a href="unidad-3-preprocesamiento-y-visualización.html#cb45-6" tabindex="-1"></a>  <span class="fu">autoplot</span>(stl_obj) <span class="sc">+</span></span>
<span id="cb45-7"><a href="unidad-3-preprocesamiento-y-visualización.html#cb45-7" tabindex="-1"></a>    <span class="fu">labs</span>(</span>
<span id="cb45-8"><a href="unidad-3-preprocesamiento-y-visualización.html#cb45-8" tabindex="-1"></a>      <span class="at">title =</span> <span class="st">&quot;Figura 13. Descomposición STL de la serie mensual&quot;</span>,</span>
<span id="cb45-9"><a href="unidad-3-preprocesamiento-y-visualización.html#cb45-9" tabindex="-1"></a>      <span class="at">subtitle =</span> <span class="cf">if</span> (usar_bc)</span>
<span id="cb45-10"><a href="unidad-3-preprocesamiento-y-visualización.html#cb45-10" tabindex="-1"></a>        <span class="fu">paste0</span>(<span class="st">&quot;Aplicando transformación Box–Cox (λ = &quot;</span>, <span class="fu">round</span>(lambda_bc,<span class="dv">3</span>), <span class="st">&quot;)&quot;</span>)</span>
<span id="cb45-11"><a href="unidad-3-preprocesamiento-y-visualización.html#cb45-11" tabindex="-1"></a>      <span class="cf">else</span></span>
<span id="cb45-12"><a href="unidad-3-preprocesamiento-y-visualización.html#cb45-12" tabindex="-1"></a>        <span class="st">&quot;Sin transformación Box–Cox&quot;</span>,</span>
<span id="cb45-13"><a href="unidad-3-preprocesamiento-y-visualización.html#cb45-13" tabindex="-1"></a>      <span class="at">x =</span> <span class="st">&quot;Tiempo&quot;</span>, <span class="at">y =</span> <span class="cn">NULL</span></span>
<span id="cb45-14"><a href="unidad-3-preprocesamiento-y-visualización.html#cb45-14" tabindex="-1"></a>    ) <span class="sc">+</span> gg_std</span>
<span id="cb45-15"><a href="unidad-3-preprocesamiento-y-visualización.html#cb45-15" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="serie-retail-au_files/figure-html/unnamed-chunk-9-1.png" width="768" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="unidad-3-preprocesamiento-y-visualización.html#cb46-1" tabindex="-1"></a><span class="cf">if</span> (usar_bc) {</span>
<span id="cb46-2"><a href="unidad-3-preprocesamiento-y-visualización.html#cb46-2" tabindex="-1"></a>  <span class="co"># Crear tabla de varianzas con formato numérico y sin notación científica</span></span>
<span id="cb46-3"><a href="unidad-3-preprocesamiento-y-visualización.html#cb46-3" tabindex="-1"></a>  var_tbl <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb46-4"><a href="unidad-3-preprocesamiento-y-visualización.html#cb46-4" tabindex="-1"></a>    <span class="at">Serie =</span> <span class="fu">c</span>(<span class="st">&quot;Original&quot;</span>, <span class="fu">paste0</span>(<span class="st">&quot;Box-Cox (lambda = &quot;</span>, <span class="fu">round</span>(lambda_bc, <span class="dv">3</span>), <span class="st">&quot;)&quot;</span>)),</span>
<span id="cb46-5"><a href="unidad-3-preprocesamiento-y-visualización.html#cb46-5" tabindex="-1"></a>    <span class="at">Varianza =</span> <span class="fu">formatC</span>(</span>
<span id="cb46-6"><a href="unidad-3-preprocesamiento-y-visualización.html#cb46-6" tabindex="-1"></a>      <span class="fu">c</span>(<span class="fu">var</span>(ts_y, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="fu">var</span>(serie_bc, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)),</span>
<span id="cb46-7"><a href="unidad-3-preprocesamiento-y-visualización.html#cb46-7" tabindex="-1"></a>      <span class="at">format =</span> <span class="st">&quot;f&quot;</span>, <span class="at">digits =</span> <span class="dv">2</span>, <span class="at">big.mark =</span> <span class="st">&quot;,&quot;</span></span>
<span id="cb46-8"><a href="unidad-3-preprocesamiento-y-visualización.html#cb46-8" tabindex="-1"></a>    )</span>
<span id="cb46-9"><a href="unidad-3-preprocesamiento-y-visualización.html#cb46-9" tabindex="-1"></a>  )</span>
<span id="cb46-10"><a href="unidad-3-preprocesamiento-y-visualización.html#cb46-10" tabindex="-1"></a></span>
<span id="cb46-11"><a href="unidad-3-preprocesamiento-y-visualización.html#cb46-11" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb46-12"><a href="unidad-3-preprocesamiento-y-visualización.html#cb46-12" tabindex="-1"></a>    var_tbl,</span>
<span id="cb46-13"><a href="unidad-3-preprocesamiento-y-visualización.html#cb46-13" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;Tabla 7. Comparación de varianzas: original vs transformada (criterio de estabilización).&quot;</span>,</span>
<span id="cb46-14"><a href="unidad-3-preprocesamiento-y-visualización.html#cb46-14" tabindex="-1"></a>    <span class="at">align =</span> <span class="st">&quot;c&quot;</span>,</span>
<span id="cb46-15"><a href="unidad-3-preprocesamiento-y-visualización.html#cb46-15" tabindex="-1"></a>    <span class="at">booktabs =</span> <span class="cn">TRUE</span></span>
<span id="cb46-16"><a href="unidad-3-preprocesamiento-y-visualización.html#cb46-16" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb46-17"><a href="unidad-3-preprocesamiento-y-visualización.html#cb46-17" tabindex="-1"></a>    kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(</span>
<span id="cb46-18"><a href="unidad-3-preprocesamiento-y-visualización.html#cb46-18" tabindex="-1"></a>      <span class="at">full_width =</span> <span class="cn">FALSE</span>,</span>
<span id="cb46-19"><a href="unidad-3-preprocesamiento-y-visualización.html#cb46-19" tabindex="-1"></a>      <span class="at">position =</span> <span class="st">&quot;center&quot;</span>,</span>
<span id="cb46-20"><a href="unidad-3-preprocesamiento-y-visualización.html#cb46-20" tabindex="-1"></a>      <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">&quot;striped&quot;</span>, <span class="st">&quot;hover&quot;</span>, <span class="st">&quot;condensed&quot;</span>)</span>
<span id="cb46-21"><a href="unidad-3-preprocesamiento-y-visualización.html#cb46-21" tabindex="-1"></a>    )</span>
<span id="cb46-22"><a href="unidad-3-preprocesamiento-y-visualización.html#cb46-22" tabindex="-1"></a>}</span></code></pre></div>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-9">Table 4.1: </span><span id="tab:unnamed-chunk-9">Table 4.2: </span>Tabla 7. Comparación de varianzas: original vs transformada (criterio de estabilización).
</caption>
<thead>
<tr>
<th style="text-align:center;">
Serie
</th>
<th style="text-align:center;">
Varianza
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Original
</td>
<td style="text-align:center;">
195,743,308.97
</td>
</tr>
<tr>
<td style="text-align:center;">
Box-Cox (lambda = 0.196)
</td>
<td style="text-align:center;">
18.20
</td>
</tr>
</tbody>
</table>
<p>Figura 13. Descomposición STL de la serie mensual</p>
<p>La descomposición STL (con transformación Box–Cox, λ = 0.196) permite analizar la estructura interna de la serie mensual Australia Monthly Retail Turnover y distinguir sus componentes principales:</p>
<p>Data (serie original transformada): muestra un comportamiento creciente a lo largo del tiempo, lo que confirma la presencia de una tendencia positiva estructural en las ventas minoristas australianas.</p>
<p>Trend (tendencia): evidencia un incremento sostenido, especialmente a partir del año 2000, reflejando el crecimiento económico y la expansión del consumo en el país.</p>
<p>Seasonal (estacionalidad): presenta un patrón cíclico muy regular y estable, con picos pronunciados en los meses de noviembre y diciembre (temporada alta por fin de año) y caídas en enero–febrero.</p>
<p>Remainder (residuo): agrupa las fluctuaciones irregulares no explicadas por los componentes sistemáticos, asociadas a choques económicos o cambios coyunturales del mercado.</p>
<p>Tabla 7. Comparación de varianzas: original vs transformada</p>
<p>La varianza de la serie se redujo drásticamente tras aplicar la transformación Box–Cox, pasando de aproximadamente 1.96×10⁸ a 18.2.</p>
<p>Esto indica que la transformación logró estabilizar la variabilidad de la serie, uno de los requisitos para que el modelo ARIMA (o SARIMA) funcione correctamente.</p>
<p>La estimación del parámetro λ = 0.196 confirma que una transformación de tipo raíz o logarítmica era necesaria para homogeneizar la escala de las observaciones.</p>
<p>La aplicación de la transformación Box–Cox fue justificada y efectiva, ya que permitió controlar la heterocedasticidad (varianza no constante) y dejar la serie en condiciones más adecuadas para el análisis de estacionariedad y la posterior estimación del modelo SARIMA.</p>
</div>
<div id="fuerza-estacional-recomendaciones-de-diferenciación" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> <strong>Fuerza estacional + recomendaciones de diferenciación</strong><a href="#fuerza-estacional-recomendaciones-de-diferenciaci%C3%B3n" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La fuerza de estacionalidad cuantifica qué tan dominante es el componente estacional frente a la variación total de la serie. Se calcula a partir de la descomposición STL mediante la siguiente fórmula:</p>
<p><span class="math display">\[F_s = 1 - \frac{Var(R_t)}{Var(S_t + R_t)}\]</span></p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-1" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>({ <span class="fu">library</span>(forecast); <span class="fu">library</span>(knitr); <span class="fu">library</span>(kableExtra) })</span>
<span id="cb47-2"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-2" tabindex="-1"></a></span>
<span id="cb47-3"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-3" tabindex="-1"></a><span class="co"># --- Fuerza de estacionalidad (a partir del STL ya calculado) ---</span></span>
<span id="cb47-4"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-4" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">exists</span>(<span class="st">&quot;stl_obj&quot;</span>), <span class="fu">exists</span>(<span class="st">&quot;serie_bc&quot;</span>))</span>
<span id="cb47-5"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-5" tabindex="-1"></a></span>
<span id="cb47-6"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-6" tabindex="-1"></a>comp   <span class="ot">&lt;-</span> stl_obj<span class="sc">$</span>time.series</span>
<span id="cb47-7"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-7" tabindex="-1"></a>var_r  <span class="ot">&lt;-</span> <span class="fu">var</span>(comp[, <span class="st">&quot;remainder&quot;</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb47-8"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-8" tabindex="-1"></a>var_sr <span class="ot">&lt;-</span> <span class="fu">var</span>(comp[, <span class="st">&quot;seasonal&quot;</span>] <span class="sc">+</span> comp[, <span class="st">&quot;remainder&quot;</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb47-9"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-9" tabindex="-1"></a>fuerza_est <span class="ot">&lt;-</span> <span class="fu">max</span>(<span class="dv">0</span>, <span class="dv">1</span> <span class="sc">-</span> var_r<span class="sc">/</span>var_sr)  <span class="co"># 0 a 1 (mayor = estacionalidad más fuerte)</span></span>
<span id="cb47-10"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-10" tabindex="-1"></a></span>
<span id="cb47-11"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-11" tabindex="-1"></a><span class="co"># --- Recomendaciones automáticas de diferencias (regular y estacional) ---</span></span>
<span id="cb47-12"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-12" tabindex="-1"></a>d_rec <span class="ot">&lt;-</span> <span class="fu">ndiffs</span>(serie_bc, <span class="at">alpha =</span> <span class="fl">0.05</span>, <span class="at">test =</span> <span class="st">&quot;adf&quot;</span>)</span>
<span id="cb47-13"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-13" tabindex="-1"></a>D_rec <span class="ot">&lt;-</span> <span class="fu">nsdiffs</span>(serie_bc, <span class="at">m =</span> <span class="dv">12</span>)</span>
<span id="cb47-14"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-14" tabindex="-1"></a></span>
<span id="cb47-15"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-15" tabindex="-1"></a><span class="co"># --- Tabla 8: estacionalidad y recomendaciones ---</span></span>
<span id="cb47-16"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-16" tabindex="-1"></a>tab8 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb47-17"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-17" tabindex="-1"></a>  <span class="at">Indicador =</span> <span class="fu">c</span>(<span class="st">&quot;Fuerza de estacionalidad (0–1)&quot;</span>, <span class="st">&quot;d recomendado&quot;</span>, <span class="st">&quot;D recomendado (m=12)&quot;</span>),</span>
<span id="cb47-18"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-18" tabindex="-1"></a>  <span class="at">Valor     =</span> <span class="fu">c</span>(<span class="fu">round</span>(fuerza_est, <span class="dv">3</span>), d_rec, D_rec)</span>
<span id="cb47-19"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-19" tabindex="-1"></a>)</span>
<span id="cb47-20"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-20" tabindex="-1"></a></span>
<span id="cb47-21"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-21" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb47-22"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-22" tabindex="-1"></a>  tab8,</span>
<span id="cb47-23"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-23" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">&quot;Tabla 8. Medida de estacionalidad y recomendaciones de diferenciación.&quot;</span>,</span>
<span id="cb47-24"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-24" tabindex="-1"></a>  <span class="at">align =</span> <span class="st">&quot;c&quot;</span>,</span>
<span id="cb47-25"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-25" tabindex="-1"></a>  <span class="at">booktabs =</span> <span class="cn">TRUE</span></span>
<span id="cb47-26"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-26" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb47-27"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-27" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>, <span class="at">position =</span> <span class="st">&quot;center&quot;</span>,</span>
<span id="cb47-28"><a href="unidad-3-preprocesamiento-y-visualización.html#cb47-28" tabindex="-1"></a>                            <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">&quot;striped&quot;</span>,<span class="st">&quot;hover&quot;</span>,<span class="st">&quot;condensed&quot;</span>))</span></code></pre></div>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-10">Table 4.3: </span><span id="tab:unnamed-chunk-10">Table 4.4: </span>Tabla 8. Medida de estacionalidad y recomendaciones de diferenciación.
</caption>
<thead>
<tr>
<th style="text-align:center;">
Indicador
</th>
<th style="text-align:center;">
Valor
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Fuerza de estacionalidad (0–1)
</td>
<td style="text-align:center;">
0.968
</td>
</tr>
<tr>
<td style="text-align:center;">
d recomendado
</td>
<td style="text-align:center;">
1.000
</td>
</tr>
<tr>
<td style="text-align:center;">
D recomendado (m=12)
</td>
<td style="text-align:center;">
1.000
</td>
</tr>
</tbody>
</table>
<p>De acuerdo a los resultados de la Tabla 8 La fuerza estacional elevada (0.968) y las recomendaciones 𝑑=1y 𝐷=1 confirman que la serie Australia Monthly Retail Turnover presenta una estructura estacional dominante y una tendencia creciente, por lo que es necesario aplicar una doble diferenciación (regular y estacional).</p>
<p>Esto garantiza que la serie cumpla con el supuesto de estacionariedad requerido para la estimación del modelo SARIMA(p,d,q)(P,D,Q)[12] en la siguiente unidad.</p>
</div>
<div id="doble-diferenciación-regular-y-estacional" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> <strong>Doble diferenciación (regular y estacional)</strong><a href="#doble-diferenciaci%C3%B3n-regular-y-estacional" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>EL objetivo es remover tendencia y patrón estacional para lograr estacionariedad.</p>
<p>Fórmulas:</p>
<p>Diferencia regular:
<span class="math display">\[\nabla Y_t = Y_t - Y_{t-1}\]</span></p>
<p>Diferencia estacional (m=12):
<span class="math display">\[\nabla_{12} Y_t = Y_t - Y_{t-12}\]</span></p>
<p>Combinada (aplicando primero estacional y luego regular):</p>
<p><span class="math display">\[\nabla \nabla_{12} Y_t = (Y_t - Y_{t-12}) - (Y_{t-1} - Y_{t-13})\]</span></p>
<p>En esta unidad usamos los órdenes recomendados: d = 1 y D = 1.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="unidad-3-preprocesamiento-y-visualización.html#cb48-1" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">exists</span>(<span class="st">&quot;serie_bc&quot;</span>))   <span class="co"># Serie (posiblemente Box–Cox) y freq=12</span></span>
<span id="cb48-2"><a href="unidad-3-preprocesamiento-y-visualización.html#cb48-2" tabindex="-1"></a>d_rec <span class="ot">&lt;-</span> <span class="dv">1</span><span class="dt">L</span></span>
<span id="cb48-3"><a href="unidad-3-preprocesamiento-y-visualización.html#cb48-3" tabindex="-1"></a>D_rec <span class="ot">&lt;-</span> <span class="dv">1</span><span class="dt">L</span></span>
<span id="cb48-4"><a href="unidad-3-preprocesamiento-y-visualización.html#cb48-4" tabindex="-1"></a></span>
<span id="cb48-5"><a href="unidad-3-preprocesamiento-y-visualización.html#cb48-5" tabindex="-1"></a>y_diff <span class="ot">&lt;-</span> serie_bc</span>
<span id="cb48-6"><a href="unidad-3-preprocesamiento-y-visualización.html#cb48-6" tabindex="-1"></a><span class="cf">if</span> (D_rec <span class="sc">&gt;</span> <span class="dv">0</span>) y_diff <span class="ot">&lt;-</span> <span class="fu">diff</span>(y_diff, <span class="at">lag =</span> <span class="dv">12</span>, <span class="at">differences =</span> D_rec)</span>
<span id="cb48-7"><a href="unidad-3-preprocesamiento-y-visualización.html#cb48-7" tabindex="-1"></a><span class="cf">if</span> (d_rec <span class="sc">&gt;</span> <span class="dv">0</span>) y_diff <span class="ot">&lt;-</span> <span class="fu">diff</span>(y_diff, <span class="at">differences =</span> d_rec)</span>
<span id="cb48-8"><a href="unidad-3-preprocesamiento-y-visualización.html#cb48-8" tabindex="-1"></a></span>
<span id="cb48-9"><a href="unidad-3-preprocesamiento-y-visualización.html#cb48-9" tabindex="-1"></a><span class="co"># Figura 14. Serie transformada y doblemente diferenciada (Δ·Δ12)</span></span>
<span id="cb48-10"><a href="unidad-3-preprocesamiento-y-visualización.html#cb48-10" tabindex="-1"></a><span class="fu">print</span>(</span>
<span id="cb48-11"><a href="unidad-3-preprocesamiento-y-visualización.html#cb48-11" tabindex="-1"></a>  <span class="fu">autoplot</span>(y_diff) <span class="sc">+</span></span>
<span id="cb48-12"><a href="unidad-3-preprocesamiento-y-visualización.html#cb48-12" tabindex="-1"></a>    <span class="fu">labs</span>(</span>
<span id="cb48-13"><a href="unidad-3-preprocesamiento-y-visualización.html#cb48-13" tabindex="-1"></a>      <span class="at">title =</span> <span class="st">&quot;Figura 14. Serie transformada y diferenciada (Δ·Δ₁₂)&quot;</span>,</span>
<span id="cb48-14"><a href="unidad-3-preprocesamiento-y-visualización.html#cb48-14" tabindex="-1"></a>      <span class="at">subtitle =</span> <span class="st">&quot;Ordenes aplicados: d = 1, D = 1 (m = 12)&quot;</span>,</span>
<span id="cb48-15"><a href="unidad-3-preprocesamiento-y-visualización.html#cb48-15" tabindex="-1"></a>      <span class="at">x =</span> <span class="st">&quot;Tiempo&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Escala transformada&quot;</span></span>
<span id="cb48-16"><a href="unidad-3-preprocesamiento-y-visualización.html#cb48-16" tabindex="-1"></a>    ) <span class="sc">+</span> gg_std</span>
<span id="cb48-17"><a href="unidad-3-preprocesamiento-y-visualización.html#cb48-17" tabindex="-1"></a>)</span></code></pre></div>
<p><img src="serie-retail-au_files/figure-html/unnamed-chunk-11-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>En la Figura 14 vemos que después de aplicar las diferencias regular (𝑑=1) y estacional (D=1,m=12), la serie Australia Monthly Retail Turnover muestra un comportamiento claramente distinto al de la versión original.</p>
<ul>
<li><p>La serie se oscila alrededor de la media cero, lo que sugiere que la tendencia fue eliminada.</p></li>
<li><p>La varianza se mantiene relativamente constante a lo largo del tiempo, indicando que el proceso de diferenciación logró estabilizar la escala.</p></li>
<li><p>Los picos irregulares observados alrededor del año 2000 podrían corresponder a eventos económicos puntuales (choques transitorios), pero no reflejan una tendencia sistemática.</p></li>
<li><p>No se aprecian patrones cíclicos definidos ni repetitivos, lo que evidencia que la estacionalidad fue removida con éxito.</p></li>
</ul>
</div>
<div id="prueba-adf-antesdespués" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> <strong>Prueba ADF antes/después</strong><a href="#prueba-adf-antesdespu%C3%A9s" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El objetivo es evidenciar estacionariedad tras la doble diferenciación.</p>
<p>Modelo (forma común de la ADF):
<span class="math display">\[\Delta Y_t = \alpha + \beta t + \gamma Y_{t-1} + \sum_{i=1}^{p}\phi_i \, \Delta Y_{t-i} + \varepsilon_t\]</span>
Hipótesis:
<span class="math display">\[H_0: \gamma = 0 \quad (\text{raíz unitaria, no estacionaria}) \qquad H_1: \gamma &lt; 0 \quad (\text{estacionaria})\]</span>
Criterio: p-value &lt; 0.05 → evidencia de estacionariedad.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="unidad-3-preprocesamiento-y-visualización.html#cb49-1" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>({ <span class="fu">library</span>(tseries); <span class="fu">library</span>(knitr); <span class="fu">library</span>(kableExtra) })</span>
<span id="cb49-2"><a href="unidad-3-preprocesamiento-y-visualización.html#cb49-2" tabindex="-1"></a></span>
<span id="cb49-3"><a href="unidad-3-preprocesamiento-y-visualización.html#cb49-3" tabindex="-1"></a>adf_before <span class="ot">&lt;-</span> <span class="fu">adf.test</span>(serie_bc)</span>
<span id="cb49-4"><a href="unidad-3-preprocesamiento-y-visualización.html#cb49-4" tabindex="-1"></a>adf_after  <span class="ot">&lt;-</span> <span class="fu">adf.test</span>(<span class="fu">na.omit</span>(y_diff))</span>
<span id="cb49-5"><a href="unidad-3-preprocesamiento-y-visualización.html#cb49-5" tabindex="-1"></a></span>
<span id="cb49-6"><a href="unidad-3-preprocesamiento-y-visualización.html#cb49-6" tabindex="-1"></a><span class="co"># Crear tabla </span></span>
<span id="cb49-7"><a href="unidad-3-preprocesamiento-y-visualización.html#cb49-7" tabindex="-1"></a>tab9 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb49-8"><a href="unidad-3-preprocesamiento-y-visualización.html#cb49-8" tabindex="-1"></a>  <span class="st">`</span><span class="at">Etapa</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;Antes (serie usada en STL)&quot;</span>, <span class="st">&quot;Después de $</span><span class="sc">\\</span><span class="st">Delta·</span><span class="sc">\\</span><span class="st">Delta_{12}$&quot;</span>),</span>
<span id="cb49-9"><a href="unidad-3-preprocesamiento-y-visualización.html#cb49-9" tabindex="-1"></a>  <span class="st">`</span><span class="at">p-value ADF</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">formatC</span>(<span class="fu">c</span>(adf_before<span class="sc">$</span>p.value, adf_after<span class="sc">$</span>p.value),</span>
<span id="cb49-10"><a href="unidad-3-preprocesamiento-y-visualización.html#cb49-10" tabindex="-1"></a>                          <span class="at">format =</span> <span class="st">&quot;f&quot;</span>, <span class="at">digits =</span> <span class="dv">3</span>),</span>
<span id="cb49-11"><a href="unidad-3-preprocesamiento-y-visualización.html#cb49-11" tabindex="-1"></a>  <span class="st">`</span><span class="at">Estacionaria</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(adf_before<span class="sc">$</span>p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>, adf_after<span class="sc">$</span>p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span>
<span id="cb49-12"><a href="unidad-3-preprocesamiento-y-visualización.html#cb49-12" tabindex="-1"></a>)</span>
<span id="cb49-13"><a href="unidad-3-preprocesamiento-y-visualización.html#cb49-13" tabindex="-1"></a></span>
<span id="cb49-14"><a href="unidad-3-preprocesamiento-y-visualización.html#cb49-14" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb49-15"><a href="unidad-3-preprocesamiento-y-visualización.html#cb49-15" tabindex="-1"></a>  tab9,</span>
<span id="cb49-16"><a href="unidad-3-preprocesamiento-y-visualización.html#cb49-16" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">&quot;Tabla 9. Prueba ADF antes y después de la doble diferenciación.&quot;</span>,</span>
<span id="cb49-17"><a href="unidad-3-preprocesamiento-y-visualización.html#cb49-17" tabindex="-1"></a>  <span class="at">align =</span> <span class="st">&quot;c&quot;</span>, <span class="at">booktabs =</span> <span class="cn">TRUE</span>, <span class="at">escape =</span> <span class="cn">FALSE</span></span>
<span id="cb49-18"><a href="unidad-3-preprocesamiento-y-visualización.html#cb49-18" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb49-19"><a href="unidad-3-preprocesamiento-y-visualización.html#cb49-19" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>, <span class="at">position =</span> <span class="st">&quot;center&quot;</span>,</span>
<span id="cb49-20"><a href="unidad-3-preprocesamiento-y-visualización.html#cb49-20" tabindex="-1"></a>                            <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">&quot;striped&quot;</span>,<span class="st">&quot;hover&quot;</span>,<span class="st">&quot;condensed&quot;</span>))</span></code></pre></div>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-12">Table 4.5: </span><span id="tab:unnamed-chunk-12">Table 4.6: </span>Tabla 9. Prueba ADF antes y después de la doble diferenciación.
</caption>
<thead>
<tr>
<th style="text-align:center;">
Etapa
</th>
<th style="text-align:center;">
p.value.ADF
</th>
<th style="text-align:center;">
Estacionaria
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Antes (serie usada en STL)
</td>
<td style="text-align:center;">
0.010
</td>
<td style="text-align:center;">
TRUE
</td>
</tr>
<tr>
<td style="text-align:center;">
Después de <span class="math inline">\(\Delta·\Delta_{12}\)</span>
</td>
<td style="text-align:center;">
0.010
</td>
<td style="text-align:center;">
TRUE
</td>
</tr>
</tbody>
</table>
<p>En la Tabla 9 podemos apreciar que en ambos casos el p-value (0.01) es menor que 0.05, por lo que se rechaza la hipótesis nula (H₀) de raíz unitaria.</p>
<p>Esto significa que tanto la serie transformada con Box–Cox como la doblemente diferenciada son estacionarias en términos de media y varianza.</p>
<p>Sin embargo, el resultado “TRUE” en ambas etapas puede deberse a que el Box–Cox ya estabilizó gran parte de la varianza, y la doble diferenciación terminó de eliminar la tendencia residual y los ciclos anuales.</p>
<p>La prueba ADF confirma que la serie procesada cumple con el supuesto de estacionariedad, lo cual valida el preprocesamiento y permite avanzar al análisis de autocorrelaciones (ACF/PACF) para determinar los órdenes del modelo SARIMA(p,d,q)(P,D,Q)[12].</p>
</div>
<div id="validación-visual-acf-y-pacf" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> <strong>Validación visual: ACF y PACF</strong><a href="#validaci%C3%B3n-visual-acf-y-pacf" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Objetivo: verificar la estacionariedad y la estructura de correlación temporal en la serie diferenciada.</p>
<p>La función de autocorrelación (ACF) mide la relación entre valores separados por un rezago k:</p>
<p><span class="math display">\[\rho_k = \frac{\text{Cov}(Y_t, Y_{t-k})}{\text{Var}(Y_t)}\]</span>
donde:</p>
<ul>
<li><span class="math inline">\(\rho_k\)</span> es el coeficiente de autocorrelación en el rezago k,</li>
<li><span class="math inline">\(Y_t\)</span> es el valor de la serie en el tiempo t.</li>
</ul>
<p>En una serie estacionaria, la ACF decae rápidamente hacia cero y no muestra patrones sistemáticos.</p>
<p>La autocorrelación parcial (PACF) mide la correlación directa entre <span class="math inline">\(Y_t\)</span> y <span class="math inline">\(Y_{t-k}\)</span>, eliminando los efectos de los rezagos intermedios.Ambas funciones ayudan a:
- Confirmar la estacionariedad de la serie diferenciada.
- Sugerir los órdenes (p, q) y (P, Q) para el modelo SARIMA.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="unidad-3-preprocesamiento-y-visualización.html#cb50-1" tabindex="-1"></a><span class="fu">Acf</span>(<span class="fu">na.omit</span>(y_diff),</span>
<span id="cb50-2"><a href="unidad-3-preprocesamiento-y-visualización.html#cb50-2" tabindex="-1"></a>    <span class="at">main =</span> <span class="st">&quot;Figura 15. Función de Autocorrelación (ACF) - Serie diferenciada Δ·Δ₁₂&quot;</span>)</span></code></pre></div>
<p><img src="serie-retail-au_files/figure-html/unnamed-chunk-13-1.png" width="768" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="unidad-3-preprocesamiento-y-visualización.html#cb51-1" tabindex="-1"></a><span class="co"># Figura 16. PACF de la serie Δ·Δ₁₂</span></span>
<span id="cb51-2"><a href="unidad-3-preprocesamiento-y-visualización.html#cb51-2" tabindex="-1"></a><span class="fu">Pacf</span>(<span class="fu">na.omit</span>(y_diff),</span>
<span id="cb51-3"><a href="unidad-3-preprocesamiento-y-visualización.html#cb51-3" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Figura 16. Función de Autocorrelación Parcial (PACF) - Serie diferenciada Δ·Δ₁₂&quot;</span>)</span></code></pre></div>
<p><img src="serie-retail-au_files/figure-html/unnamed-chunk-13-2.png" width="768" style="display: block; margin: auto;" /></p>
<p>Figura 15. Función de Autocorrelación (ACF)</p>
<p>La función de autocorrelación de la serie diferenciada (Δ·Δ₁₂) muestra una rápida caída de las correlaciones después de los primeros rezagos, lo que indica que no existe dependencia temporal prolongada.
Los picos en los primeros lags son bajos y dentro del intervalo de confianza (líneas azules), lo que confirma que no hay estructura de tendencia ni estacionalidad remanente.
Además, los rezagos en múltiplos de 12 no presentan un patrón fuerte, evidenciando que la diferenciación estacional eliminó efectivamente la periodicidad anual observada en la serie original.</p>
<p>Figura 16. Función de Autocorrelación Parcial (PACF)</p>
<p>En la PACF, los picos significativos se concentran en los primeros rezagos (lag 1), mientras que los demás coeficientes se encuentran dentro de las bandas de confianza.
Este patrón —un corte abrupto en la PACF y una ACF que decae gradualmente— sugiere la presencia de un término autorregresivo (AR) de primer orden.</p>
<p>Los resultados combinados de las Figuras 15 y 16 confirman que la serie diferenciada ya cumple con el supuesto de estacionariedad, con media constante, varianza homogénea y ausencia de patrones estacionales o tendencias residuales.
De acuerdo con los patrones observados, un modelo inicial adecuado para evaluar sería:</p>
<p>SARIMA(1,1,1)(0,1,1)12</p>
<p>Este modelo integra un componente autorregresivo y otro de media móvil en la parte regular, junto con una diferencia y un término estacional de orden anual.</p>
<p>El modelo SARIMA (Seasonal ARIMA) amplía el ARIMA tradicional incorporando componentes estacionales.</p>
<p>Su formula general es:</p>
<p><span class="math display">\[SARIMA(p,d,q)(P,D,Q)_{m}\]</span></p>
<p>donde:
* <span class="math inline">\(p\)</span> → orden autorregresivo (AR),
* <span class="math inline">\(d\)</span> → número de diferencias regulares,
* <span class="math inline">\(q\)</span> → orden de media móvil (MA),
* <span class="math inline">\(P\)</span> → orden autorregresivo estacional,
* <span class="math inline">\(D\)</span> → número de diferencias estacionales,
* <span class="math inline">\(Q\)</span> → orden de media móvil estacional,
* <span class="math inline">\(m\)</span> → periodicidad (12 para datos mensuales).</p>
<p>Este checklist resume las decisiones y verificaciones realizadas en el preprocesamiento.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-1" tabindex="-1"></a>check_tbl <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb52-2"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-2" tabindex="-1"></a>  <span class="st">`</span><span class="at">Aspecto evaluado</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(</span>
<span id="cb52-3"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-3" tabindex="-1"></a>    <span class="st">&quot;Transformacion Box-Cox aplicada&quot;</span>,</span>
<span id="cb52-4"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-4" tabindex="-1"></a>    <span class="st">&quot;Diferencias aplicadas (d, D)&quot;</span>,</span>
<span id="cb52-5"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-5" tabindex="-1"></a>    <span class="st">&quot;Prueba ADF final (p-value &lt; 0.05)&quot;</span>,</span>
<span id="cb52-6"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-6" tabindex="-1"></a>    <span class="st">&quot;Confirmacion visual (ACF / PACF)&quot;</span>,</span>
<span id="cb52-7"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-7" tabindex="-1"></a>    <span class="st">&quot;Serie lista para modelado SARIMA&quot;</span></span>
<span id="cb52-8"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-8" tabindex="-1"></a>  ),</span>
<span id="cb52-9"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-9" tabindex="-1"></a>  <span class="st">`</span><span class="at">Resultado / Evidencia</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(</span>
<span id="cb52-10"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-10" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">exists</span>(<span class="st">&quot;lambda_bc&quot;</span>) <span class="sc">&amp;&amp;</span> <span class="fu">abs</span>(lambda_bc <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">&gt;</span> <span class="fl">0.1</span>)</span>
<span id="cb52-11"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-11" tabindex="-1"></a>      <span class="fu">paste0</span>(<span class="st">&quot;Si, lambda = &quot;</span>, <span class="fu">round</span>(lambda_bc, <span class="dv">3</span>))</span>
<span id="cb52-12"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-12" tabindex="-1"></a>    <span class="cf">else</span></span>
<span id="cb52-13"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-13" tabindex="-1"></a>      <span class="st">&quot;No necesaria (lambda ≈ 1)&quot;</span>,</span>
<span id="cb52-14"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-14" tabindex="-1"></a>    <span class="st">&quot;d = 1, D = 1 (m = 12)&quot;</span>,</span>
<span id="cb52-15"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-15" tabindex="-1"></a>    <span class="fu">ifelse</span>(adf_after<span class="sc">$</span>p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>, <span class="st">&quot;Si - estacionaria&quot;</span>, <span class="st">&quot;No - requiere mas diferencias&quot;</span>),</span>
<span id="cb52-16"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-16" tabindex="-1"></a>    <span class="st">&quot;ACF y PACF confirman estacionariedad y estructura AR(1)/MA(1)&quot;</span>,</span>
<span id="cb52-17"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-17" tabindex="-1"></a>    <span class="fu">ifelse</span>(adf_after<span class="sc">$</span>p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>, <span class="st">&quot;Si - lista para modelar&quot;</span>, <span class="st">&quot;Ajustar diferenciacion&quot;</span>)</span>
<span id="cb52-18"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-18" tabindex="-1"></a>  )</span>
<span id="cb52-19"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-19" tabindex="-1"></a>)</span>
<span id="cb52-20"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-20" tabindex="-1"></a></span>
<span id="cb52-21"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-21" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb52-22"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-22" tabindex="-1"></a>  check_tbl,</span>
<span id="cb52-23"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-23" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">&quot;Tabla 10. Checklist final de preprocesamiento para el modelo SARIMA(p,d,q)(P,D,Q)[12].&quot;</span>,</span>
<span id="cb52-24"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-24" tabindex="-1"></a>  <span class="at">align =</span> <span class="st">&quot;c&quot;</span>,</span>
<span id="cb52-25"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-25" tabindex="-1"></a>  <span class="at">booktabs =</span> <span class="cn">TRUE</span>,</span>
<span id="cb52-26"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-26" tabindex="-1"></a>  <span class="at">escape =</span> <span class="cn">FALSE</span></span>
<span id="cb52-27"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-27" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb52-28"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-28" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>, <span class="at">position =</span> <span class="st">&quot;center&quot;</span>,</span>
<span id="cb52-29"><a href="unidad-3-preprocesamiento-y-visualización.html#cb52-29" tabindex="-1"></a>                            <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">&quot;striped&quot;</span>,<span class="st">&quot;hover&quot;</span>,<span class="st">&quot;condensed&quot;</span>))</span></code></pre></div>
<table class="table table-striped table-hover table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-14">Table 4.7: </span><span id="tab:unnamed-chunk-14">Table 4.8: </span>Tabla 10. Checklist final de preprocesamiento para el modelo SARIMA(p,d,q)(P,D,Q)[12].
</caption>
<thead>
<tr>
<th style="text-align:center;">
Aspecto.evaluado
</th>
<th style="text-align:center;">
Resultado…Evidencia
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
Transformacion Box-Cox aplicada
</td>
<td style="text-align:center;">
Si, lambda = 0.196
</td>
</tr>
<tr>
<td style="text-align:center;">
Diferencias aplicadas (d, D)
</td>
<td style="text-align:center;">
d = 1, D = 1 (m = 12)
</td>
</tr>
<tr>
<td style="text-align:center;">
Prueba ADF final (p-value &lt; 0.05)
</td>
<td style="text-align:center;">
Si - estacionaria
</td>
</tr>
<tr>
<td style="text-align:center;">
Confirmacion visual (ACF / PACF)
</td>
<td style="text-align:center;">
ACF y PACF confirman estacionariedad y estructura AR(1)/MA(1)
</td>
</tr>
<tr>
<td style="text-align:center;">
Serie lista para modelado SARIMA
</td>
<td style="text-align:center;">
Si - lista para modelar
</td>
</tr>
</tbody>
</table>
<p>La Tabla 10 resume los pasos y comprobaciones realizados durante el preprocesamiento de la serie mensual Australia Monthly Retail Turnover (1982–2024):</p>
<table>
<colgroup>
<col width="45%" />
<col width="54%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"><strong>Aspecto evaluado</strong></th>
<th align="left"><strong>Interpretación</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><strong>Transformación Box-Cox aplicada</strong></td>
<td align="left">Se aplicó la transformación Box-Cox con λ = 0.196, lo que redujo significativamente la varianza y estabilizó la escala de la serie. Esta corrección permitió controlar la heterocedasticidad y cumplir con los supuestos de varianza constante requeridos por los modelos ARIMA/SARIMA.</td>
</tr>
<tr class="even">
<td align="left"><strong>Diferencias aplicadas (d, D)</strong></td>
<td align="left">La combinación de d = 1 y D = 1 (m = 12) eliminó tanto la tendencia como el patrón estacional anual, dejando la serie centrada en torno a una media estable.</td>
</tr>
<tr class="odd">
<td align="left"><strong>Prueba ADF final (p-value &lt; 0.05)</strong></td>
<td align="left">Con un p-value = 0.010, se rechaza la hipótesis nula de raíz unitaria. La serie presenta evidencia estadística de estacionariedad después del proceso de diferenciación.</td>
</tr>
<tr class="even">
<td align="left"><strong>Confirmación visual (ACF / PACF)</strong></td>
<td align="left">Los gráficos ACF y PACF muestran un rápido decaimiento de las correlaciones, sin patrones periódicos marcados, lo que confirma la estacionariedad y sugiere una estructura AR(1)/MA(1) de bajo orden.</td>
</tr>
<tr class="odd">
<td align="left"><strong>Serie lista para modelado SARIMA</strong></td>
<td align="left">La serie procesada cumple los supuestos de estacionariedad, por lo que está lista para la estimación del modelo SARIMA(1,1,1)(0,1,1)[12] como punto de partida para la siguiente unidad.</td>
</tr>
</tbody>
</table>
</div>
<div id="conclusiones-unidad-3" class="section level2 hasAnchor" number="4.6">
<h2><span class="header-section-number">4.6</span> <strong>Conclusiones unidad 3</strong><a href="unidad-3-preprocesamiento-y-visualización.html#conclusiones-unidad-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El preprocesamiento realizado en la Unidad 3 permitió consolidar la preparación de la serie mensual Australia Monthly Retail Turnover (1982–2024) para su futura modelación mediante técnicas SARIMA. A través de transformaciones estadísticas y validaciones gráficas, se garantizó que la serie cumpliera los supuestos de estacionariedad, condición fundamental para el análisis de series de tiempo.</p>
<p>En primer lugar, la aplicación de la transformación Box–Cox (λ = 0.196) redujo de manera significativa la varianza y estabilizó la escala, mejorando la homogeneidad de los datos. Posteriormente, la doble diferenciación (d = 1, D = 1, m = 12) eliminó la tendencia y los patrones estacionales anuales, lo cual se reflejó en una serie con media constante y comportamiento aleatorio alrededor del cero.</p>
<p>La prueba ADF (p-value = 0.01) confirmó estadísticamente que la serie diferenciada es estacionaria, mientras que el análisis visual de las funciones ACF y PACF evidenció la ausencia de autocorrelaciones prolongadas y la presencia de picos iniciales compatibles con componentes AR(1) y MA(1). Estos resultados validan el correcto preprocesamiento de los datos y orientan la estructura base para la estimación del modelo.</p>
<p>Finalmente, los resultados obtenidos en el checklist de preprocesamiento (Tabla 10) verifican que la serie está lista para su modelado. Como punto de partida, se recomienda evaluar el modelo SARIMA(1,1,1)(0,1,1)[12], el cual integrará los componentes identificados y permitirá realizar pronósticos robustos sobre el comportamiento futuro de las ventas minoristas australianas.</p>
</div>
<div id="referencias" class="section level2 hasAnchor" number="4.7">
<h2><span class="header-section-number">4.7</span> <strong>Referencias</strong><a href="unidad-3-preprocesamiento-y-visualización.html#referencias" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p>Universidad Javeriana Cali (2025). <em>Material del curso Análisis de Series de Tiempo — Unidad 2: Estructura de los datos en series de tiempo</em>. Aula Digital PUJ Cali.</p></li>
<li><p>Kaggle (2023). <em>Australia Monthly Retail Turnover Data</em>. Generado de <a href="https://www.kaggle.com/datasets/kanyaweechomming101/australia-monthly-retail-turnover-data">https://www.kaggle.com/datasets/kanyaweechomming101/australia-monthly-retail-turnover-data</a>.</p></li>
<li><p>Hyndman, R. J, &amp; Athanasopoulos, G. (2021). <em>Forecasting: Principles and Practice</em>. Generado de <a href="https://otexts.com/fpp3/">https://otexts.com/fpp3/</a></p></li>
</ul>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="unidad-2.-análisis-descriptivo-y-estructural-de-una-serie-temporal-tendencia-estacionalidad-y-estacionariedad.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="unidad-4-metodología-holter-winter-y-suavizamiento-a-la-variable-tiempo.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
